// Generated by CoffeeScript 1.9.3

/**
 * api
 * @module cnode/api
 * @author vfasky <vfasky@gmail.com>
 */

(function() {
  define('cnode/api', ['jquery'], function($) {
    "use strict";
    var _host, exports;
    _host = 'https://cnodejs.org';
    return exports = {
      topics: function(data) {
        if (data == null) {
          data = {};
        }
        data = $.extend({
          mdrender: false,
          limit: 10
        }, data);
        return $.get(_host + '/api/v1/topics', data);
      }
    };
  });

}).call(this);
