// Generated by CoffeeScript 1.9.3

/**
 * 过滤函数
 * @module cnode/formatters
 * @author vfasky <vfasky@gmail.com>
 */

(function() {
  define('cnode/formatters', ['mcore', 'moment', 'markdown-it'], function(mcore, moment, Markdownit) {
    "use strict";
    var Template, markdown;
    Template = mcore.Template;
    markdown = new Markdownit({
      html: false,
      xhtmlOut: false,
      breaks: true,
      langPrefix: 'language-',
      linkify: true,
      typographer: false
    });
    Template.formatters('dateFormat', function(value, format) {
      if (format == null) {
        format = 'YYYY-MM-DD';
      }
      return moment(value).format(format);
    });
    Template.formatters('fromNow', function(value) {
      return moment(value).fromNow();
    });
    return Template.formatters('markdown', function(value) {
      return markdown.render(value);
    });
  });

}).call(this);
