// Generated by CoffeeScript 1.9.3

/**
 * 首页
 * @module cnode/index
 * @author vfasky <vfasky@gmail.com>
 */

(function() {
  define('cnode/index', ['jquery', 'cnode/view', 'mcore-attr/scroller'], function($, View) {
    "use strict";
    return View.subclass({
      constructor: View.prototype.constructor,
      run: function(tab) {
        return this.render('cnode/index.html', {
          topics: this.api.topics()
        });
      },
      watch: function() {
        return this.on('render', function() {
          var $scroller;
          $scroller = this.$el.find('.scroller');
          return console.log($scroller.data('scroller'));
        });
      }
    });
  });

}).call(this);
