// Generated by CoffeeScript 1.9.3

/**
 * 用户主页
 * @module cnode/user
 * @author vfasky <vfasky@gmail.com>
 */

(function() {
  "use strict";
  var View;

  View = require('./view');

  require('./formatters');

  require('mcoreExt');

  module.exports = View.subclass({
    constructor: View.prototype.constructor,
    run: function(userName) {
      return this.render('cnode/user.html', {
        user: this.api.user(userName)
      });
    }
  });

  module.exports.viewName = 'user';

}).call(this);
