// Generated by CoffeeScript 1.9.3

/**
 * 用户主页
 * @module cnode/user
 * @author vfasky <vfasky@gmail.com>
 */

(function() {
  define('cnode/user', ['jquery', 'cnode/view', 'cnode/formatters', 'mcore-attr/scroller'], function($, View) {
    "use strict";
    return View.subclass({
      constructor: View.prototype.constructor,
      run: function(userName) {
        return this.render('cnode/user.html', {
          user: this.api.user(userName)
        });
      }
    });
  });

}).call(this);
