// Generated by CoffeeScript 1.9.3

/**
 * 
 * @module cnode/view
 * @author vfasky <vfasky@gmail.com>
 */

(function() {
  "use strict";
  var api, mcore;

  mcore = require('mcoreExt');

  api = require('./api');

  module.exports = mcore.View.subclass({
    constructor: mcore.View.prototype.constructor,
    beforeInit: function() {
      return this.api = api;
    }
  });

}).call(this);
