// Generated by CoffeeScript 1.9.3

/**
 * app test
 * @module case/app
 * @author vfasky <vfasky@gmail.com>
 */


/**
 * test home
 * @module view/home
 * @author vfasky <vfasky@gmail.com>
 */

(function() {
  define('view/home', ['jquery', 'mcore/view'], function($, View) {
    "use strict";
    return View.subclass({
      constructor: View.prototype.constructor,
      run: function() {
        this.$el.html('welcome');
        return this.runShow();
      },
      runShow: function() {
        return this.app.router.match('/test/show/1');
      }
    });
  });


  /**
   * test show
   * @module view/show
   * @author vfasky <vfasky@gmail.com>
   */

  define('view/show', ['jquery', 'mcore/view'], function($, View) {
    "use strict";
    return View.subclass({
      constructor: View.prototype.constructor,
      run: function(id) {
        return this.$el.html(id);
      }
    });
  });

  define('case/app', ['describe', 'it', 'mcore/view', 'assert', 'jquery', 'mcore/app'], function(describe, it, View, assert, $, App) {
    "use strict";
    return describe('app test', function() {
      return it('router', function(done) {
        var $el, app;
        $el = $('<div />');
        app = new App($el);
        app.route('/test/show/:id', 'view/show').route('*', 'view/home');
        app.on('runView', function(view) {
          var ref;
          if (view.name === 'view/show') {
            ref = view.instantiate.$el.text();
            if (ref === '1') {
              return done();
            }
          }
        });
        return app.run();
      });
    });
  });

}).call(this);
