// Generated by CoffeeScript 1.9.3

/**
 * React Template
 * @date 2015-09-25 11:00:28
 * @author vfasky <vfasky@gmail.com>
 * @link http://vfasky.com
 * @version $Id$
 */


/**
 * test view
 * @module view/test
 * @author vfasky <vfasky@gmail.com>
 */

(function() {
  define('view/test', ['mcore/rview'], function(View) {
    "use strict";
    return View({
      init: function() {
        return this.render('test/rtpl');
      }
    });
  });

  define('view/test2', ['mcore/rview'], function(View) {
    "use strict";
    return View({
      init: function() {
        return this.render('test/rtpl2');
      }
    });
  });

  define('case/rtpl', ['describe', 'it', 'assert', 'jquery', 'mcore/rtemplate', 'mcore/rview', 'mcore/rapp'], function(describe, it, assert, $, Template, View, App) {
    "use strict";
    return describe('React Template base', function() {
      it('hello word', function() {
        var div, view;
        div = $('<div/>');
        view = new Template('hello');
        return view.render('test/rtpl').then(function(res) {
          Template.render(res.View, res.data, div[0]);
          return console.log(div[0]);
        });
      });
      return it('react app', function() {
        var app, div;
        div = $('<div/>');
        app = new App(div[0]);
        app.use(function(err, next) {
          console.log(this);
          return next();
        });
        app.route('/test', 'view/test2');
        app.route('*', 'view/test');
        app.router.match('/');
        return setTimeout(function() {
          return app.router.match('/test');
        }, 1000);
      });
    });
  });

}).call(this);
