// Generated by CoffeeScript 1.9.3

/**
 * View
 * @module mcore/view
 * @author vfasky <vfasky@gmail.com>
 */

(function() {
  define('mcore/view', ['jquery', 'mcore/template', 'stapes', 'mcore/util'], function($, Template, Stapes, util) {
    "use strict";
    var $body, $win, _isIOS, _isWeixinBrowser;
    $win = $(window);
    $body = $('body');
    _isWeixinBrowser = /MicroMessenger/i.test(window.navigator.userAgent);
    _isIOS = /iphone|ipad/gi.test(window.navigator.appVersion);
    return Stapes.subclass({
      constructor: function($el, app) {
        this.$el = $el;
        this.app = app;
        this.$win = $win;
        this.$body = $body;
        this.util = util;
        this.isWeixinBrowser = _isWeixinBrowser;
        this.isIOS = _isIOS;
        this.tpl = false;
        this.beforeInit();
        return this.init();
      },
      clone: function(value) {
        return util.clone(value);
      },
      setTitle: function(title) {
        var $iframe;
        this.title = title;
        if (document.title === this.title) {
          return;
        }
        document.title = this.title;
        if (this.isWeixinBrowser && this.isIOS) {
          $iframe = $('<iframe src="/favicon.ico"></iframe>');
          return $iframe.one('load', function() {
            return setTimeout(function() {
              return $iframe.remove();
            }, 0);
          }).appendTo(this.$body);
        }
      },
      render: function(uri, data) {
        var dtd, keys;
        if (data == null) {
          data = {};
        }
        keys = Object.keys(data);
        dtd = $.Deferred();
        if (keys.length > 0) {
          keys.forEach((function(_this) {
            return function(k) {
              return _this.set(k, {});
            };
          })(this));
        }
        if (this.tpl) {
          this.tpl.update(data);
          dtd.resolve();
          this.emit('tplUpdate');
        } else {
          Template.loadTpl(uri).done((function(_this) {
            return function(html) {
              _this.$el.append(html);
              _this.tpl = new Template(_this, data);
              dtd.resolve();
              return _this.emit('render');
            };
          })(this)).reject(function(err) {
            return dtd.reject(err || 'Template init error');
          });
        }
        return dtd.promise();
      },
      when: function() {
        return $.when.apply(this, arguments);
      },
      beforeInit: function() {},
      init: function() {},
      run: function() {},
      afterRun: function() {},
      watch: function() {}
    });
  });

}).call(this);
