// Generated by CoffeeScript 1.9.3

/**
 * 自定义tag
 * @module tag
 * @author vfasky <vfasky@gmail.com>
 */

(function() {
  define('tag', ['tag/topHeader'], function() {
    "use strict";
  });

}).call(this);
