// Generated by CoffeeScript 1.9.3

/**
 * 通用顶部
 * <top-header title="self:title" back="self.back" />
 * @module tag/topHead
 * @author vfasky <vfasky@gmail.com>
 */

(function() {
  "use strict";
  var mcore;

  mcore = require('mcore');

  mcore.Template.regTag('top-header', {
    attr: ['title', 'back'],
    template: function() {
      return '<div class="bar bar-header bar-royal">\n    <button rv-on-click="back" class="button button-icon icon ion-ios-arrow-thin-left"></button>\n\n    <h1 class="title" rv-text="title | substr 0 13"></h1>\n</div>';
    },
    init: function(el, data) {
      return data;
    }
  });

}).call(this);
