// Generated by CoffeeScript 1.9.3

/**
 *
 * @module tpl/test
 * @author vfasky <vfasky@gmail.com>
 */

(function() {
  define('tpl/test', [], function() {
    "use strict";
    var exports;
    exports = {};
    exports['t1'] = '<div>hello</div>';
    exports['t2'] = '<div class="t1" rv-each-v="self:testData">\n    {v}\n</div>';
    exports['t3'] = '<div rv-test>...</div>';
    exports['t4'] = '<div rv-test="self:t">...</div>';
    exports['t5'] = '<test list="self:data" />';
    return exports;
  });

}).call(this);
