// Generated by CoffeeScript 1.9.3

/**
 * attr ext
 * @module mcore-attr
 * @author vfasky <vfasky@gmail.com>
 */

(function() {
  "use strict";
  var exports, mcore, validator;

  validator = require('./validator');

  mcore = require('mcore');

  require('./scroller');

  mcore.ext = {
    validator: validator
  };

  exports = module.exports = mcore;

}).call(this);
