// Generated by CoffeeScript 1.10.0

/**
 * attr ext
 * @module mcore.ext
 * @author vfasky <vfasky@gmail.com>
 */
"use strict";
var exports, mcore, validator;

validator = require('./attrValidator');

require('./attrScroller');

mcore = require('mcore');

mcore.ext = {
  validator: validator
};

exports = module.exports = mcore;
