// Generated by CoffeeScript 1.10.0

/**
 * attr ext
 * @module mcore.ext
 * @author vfasky <vfasky@gmail.com>
 */
"use strict";
var exports, mcore;

require('./attrScroller');

mcore = require('mcore');

mcore.ext = {
  validator: require('./attrValidator'),
  http: require('./http')
};

exports = module.exports = mcore;
