// Generated by CoffeeScript 1.10.0

/**
 * 
 * @date 2016-01-09 14:12:49
 * @author vfasky <vfasky@gmail.com>
 * @link http://vfasky.com
 */
'use strict';
module.exports = {
  tpl: require('./tpl/test.html')
};
