// Generated by CoffeeScript 1.10.0

/**
 * 
 * @date 2016-01-26 09:41:52
 * @author vfasky <vfasky@gmail.com>
 * @link http://vfasky.com
 */
'use strict';
var Component, Template, Time, ref,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

ref = require('mcore'), Template = ref.Template, Component = ref.Component;

Time = (function(superClass) {
  extend(Time, superClass);

  function Time() {
    return Time.__super__.constructor.apply(this, arguments);
  }

  Time.prototype.init = function() {
    this.on('rendered', (function(_this) {
      return function() {
        return setTimeout(function() {
          return _this.set('time', new Date());
        }, 1000);
      };
    })(this));
    return this.render(require('./tpl/tagTime.html'), {
      time: new Date()
    });
  };

  return Time;

})(Component);

Template.components.time = Time;
