// Generated by CoffeeScript 1.10.0

/**
 * 
 * @date 2016-01-29 15:44:12
 * @author vfasky <vfasky@gmail.com>
 * @link http://vfasky.com
 */
'use strict';
var Index, View,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

View = require('mcoreApp').View;

Index = (function(superClass) {
  extend(Index, superClass);

  function Index() {
    return Index.__super__.constructor.apply(this, arguments);
  }

  Index.prototype.run = function() {
    return this.render(require('../tpl/index.html'));
  };

  return Index;

})(View);

module.exports = Index;

module.exports.viewName = 'index';
