// Generated by CoffeeScript 1.10.0

/**
 * app
 * @module mcore/app
 * @author vfasky <vfasky@gmail.com>
 */
"use strict";
var $, App, EventEmitter, ref, route, util,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

$ = require('jquery');

route = require('./route');

ref = require('mcore'), util = ref.util, EventEmitter = ref.EventEmitter;

App = (function(superClass) {
  extend(App, superClass);

  function App($el1, options) {
    this.$el = $el1;
    if (options == null) {
      options = {};
    }
    this.options = $.extend({
      viewClass: 'mcore-app-view',
      routeChange: route.Route.changeByLocationHash
    }, options);
    this.router = new route.Route(this.options.routeChange);
    this.curView = null;
    this._onLoadViw = false;
    this._middlewares = [];
    return;
  }

  App.prototype.route = function(path, viewName) {
    var self;
    self = this;
    this.router.add(path, function() {
      return self.runView(viewName, this, arguments);
    });
    return this;
  };

  App.prototype.use = function(middleware) {
    this._middlewares.push(middleware);
    return this;
  };

  App.prototype._runView = function(done) {
    if (done == null) {
      done = function() {};
    }
    this.curView.instantiate.route = this.env.route;
    this.curView.instantiate.context = this.env.context;
    this.curView.instantiate.run.apply(this.curView.instantiate, this.env.args);
    this.emit('runView', this.curView);
    return done(this.curView.instantiate);
  };

  App.prototype.stack = function(ix, err, done) {
    var middleware, next, nextIx;
    if (ix == null) {
      ix = 0;
    }
    if (err == null) {
      err = null;
    }
    if (done == null) {
      done = function() {};
    }
    if (ix === this._middlewares.length) {
      return this._runView(done);
    }
    middleware = this._middlewares[ix];
    nextIx = ix + 1;
    next = (function(_this) {
      return function(err) {
        return _this.stack(nextIx, err, done);
      };
    })(this);
    this.env.view = this.curView.instantiate;
    return middleware.call(this.env, err, next);
  };

  App.prototype.runMiddlewares = function(done) {
    if (done == null) {
      done = function() {};
    }
    if (this._middlewares.length === 0) {
      return this._runView(done);
    }
    return this.stack(0, null, done);
  };

  App.prototype._initView = function(View, viewName) {
    var $el;
    $el = $("<div class='" + this.options.viewClass + "' />");
    this.curView = {
      name: viewName,
      instantiate: new View($el, this)
    };
    return this.runMiddlewares((function(_this) {
      return function() {
        _this.curView.instantiate.$el.appendTo(_this.$el);
        _this.curView.instantiate.afterRun();
        return _this._onLoadViw = false;
      };
    })(this));
  };

  App.prototype.runView = function(View, route, args) {
    var viewName;
    if (this._onLoadViw) {
      return;
    }
    viewName = View.viewName;
    this.env = {
      route: route,
      context: route.context,
      args: args,
      viewName: viewName,
      app: this
    };
    if (this.curView) {
      if (this.curView.name === viewName) {
        this.runMiddlewares((function(_this) {
          return function() {
            return _this.curView.instantiate.afterRun();
          };
        })(this));
        return;
      } else {
        this.emit('destroyView', this.curView);
        this.curView.instantiate.destroy();
        this.curView = null;
      }
    }
    this._onLoadViw = true;
    return this._initView(View, viewName);
  };

  App.prototype.run = function() {
    return this.router.run();
  };

  return App;

})(EventEmitter);

module.exports = App;
