// Generated by CoffeeScript 1.10.0

/**
 * 
 * @date 2016-01-26 15:20:09
 * @author vfasky <vfasky@gmail.com>
 * @link http://vfasky.com
 */
'use strict';
var $, $body, $win, BaseClass, EventEmitter, Template, _id, _isIOS, _isWeixinBrowser, loadPromise, ref, util,
  slice = [].slice,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

ref = require('mcore'), EventEmitter = ref.EventEmitter, Template = ref.Template, util = ref.util;

$ = require('jquery');

$win = $(window);

$body = $('body');

_isWeixinBrowser = /MicroMessenger/i.test(window.navigator.userAgent);

_isIOS = /iphone|ipad/gi.test(window.navigator.appVersion);

_id = 0;

loadPromise = function(data) {
  var dtd, keys, promises;
  dtd = $.Deferred();
  keys = util.objectKeys(data);
  if (keys.length === 0) {
    dtd.resolve({});
  } else {
    promises = [];
    each(keys, function(v) {
      return promises.push(data[v]);
    });
    $.when.apply(null, promises).done(function() {
      var args, vData;
      args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
      vData = {};
      util.each(args, (function(_this) {
        return function(v, k) {
          var key;
          key = keys[k];
          if (key) {
            if (util.isArray(v) && v.length === 3 && v[2].promise) {
              v = v[0];
            }
            return vData[key] = v;
          }
        };
      })(this));
      return dtd.resolve(vData);
    }).fail(function(err) {
      return dtd.reject(err);
    });
  }
  return dtd.promise();
};

BaseClass = (function(superClass) {
  extend(BaseClass, superClass);

  function BaseClass() {
    this._id = _id++;
    this.$win = $win;
    this.$body = $body;
    this.util = util;
    this.nextTick = util.nextTick;
    this.isWeixinBrowser = _isWeixinBrowser;
    this.isIOS = _isIOS;
    this.template = false;
    this.beforeInit();
    this.init();
    this.watch();
  }

  BaseClass.prototype.beforeInit = function() {};

  BaseClass.prototype.init = function() {};

  BaseClass.prototype.watch = function() {};

  BaseClass.prototype.render = function(virtualDomDefine, scope) {
    var dtd;
    this.virtualDomDefine = virtualDomDefine;
    if (scope == null) {
      scope = {};
    }
    if (!this.template) {
      this.template = new Template();
    }
    dtd = $.Deferred();
    loadPromise(scope).then((function(_this) {
      return function(scope) {
        return _this.template.render(_this.virtualDomDefine, scope, function(refs) {
          return dtd.resolve(refs);
        });
      };
    })(this)).fail(function(err) {
      return dtd.reject(err);
    });
    return dtd.promise();
  };

  BaseClass.prototype.set = function(key, value) {
    if (!this.template) {
      return;
    }
    if (util.isFunction(value.then)) {
      return value.then((function(_this) {
        return function(val) {
          return _this.template.set(key, val);
        };
      })(this));
    } else {
      return this.template.set(key, value);
    }
  };

  BaseClass.prototype.get = function() {
    if (this.template) {
      return this.template.get.apply(this.template, arguments);
    }
  };

  BaseClass.prototype.remove = function() {
    if (this.template) {
      return this.template.remove.apply(this.template, arguments);
    }
  };

  BaseClass.prototype.clone = function(value) {
    return util.extend(true, value);
  };

  BaseClass.prototype.destroy = function() {
    if (this.template) {
      return this.template.destroy();
    }
  };

  BaseClass.prototype.when = function() {
    return $.when.apply(this, arguments);
  };

  return BaseClass;

})(EventEmitter);

module.exports = BaseClass;
