// Generated by CoffeeScript 1.10.0

/**
 * view 
 * @date 2016-01-26 15:10:13
 * @author vfasky <vfasky@gmail.com>
 * @link http://vfasky.com
 */
'use strict';
var $, Template, View, ref, util,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

ref = require('mcore'), Template = ref.Template, util = ref.util;

$ = require('jquery');

View = (function(superClass) {
  extend(View, superClass);

  function View($el, app) {
    this.$el = $el;
    this.app = app;
    View.__super__.constructor.call(this);
    this.once('rendered', (function(_this) {
      return function(refs) {
        return _this.$el[0].appendChild(refs);
      };
    })(this));
  }

  View.prototype.setTitle = function(title) {
    var $iframe;
    this.title = title;
    if (document.title === this.title) {
      return;
    }
    document.title = this.title;
    if (this.isWeixinBrowser && this.isIOS) {
      $iframe = $('<iframe src="/favicon.ico"></iframe>');
      return $iframe.one('load', function() {
        return setTimeout(function() {
          return $iframe.remove();
        }, 0);
      }).appendTo(this.$body);
    }
  };

  View.prototype.back = function() {
    if (window.history.length > 1) {
      window.history.back();
    } else {
      window.location.href = '#';
    }
    return false;
  };

  View.prototype.destroy = function() {
    View.__super__.destroy.call(this);
    return this.$el.remove();
  };

  View.prototype.run = function() {};

  View.prototype.afterRun = function() {};

  return View;

})(require('./baseClass'));

module.exports = View;
