// Generated by CoffeeScript 1.9.3

/**
 * 属性扩展
 * @module attr
 * @author vfasky <vfasky@gmail.com>
 */

(function() {
  define('attr', ['attr/linkToBlank'], function() {
    "use strict";
  });

}).call(this);
