// Generated by CoffeeScript 1.9.3

/**
 * 中间件
 * @module middleware
 * @author vfasky <vfasky@gmail.com>
 */

(function() {
  "use strict";
  var exports;

  exports = module.exports = {
    loader: require('./loader')
  };

}).call(this);
