// Generated by CoffeeScript 1.9.3

/**
 * 中间件
 * @module middleware
 * @author vfasky <vfasky@gmail.com>
 */

(function() {
  define('middleware', ['middleware/loader'], function(loader) {
    "use strict";
    var exports;
    return exports = {
      loader: loader
    };
  });

}).call(this);
