// Generated by CoffeeScript 1.9.3

/**
 * loading 效果
 * @module middleware/loader
 * @author vfasky <vfasky@gmail.com>
 */

(function() {
  define('middleware/loader', ['jquery'], function($) {
    "use strict";
    var $el;
    $el = $('<div class="loader-wrap">\n    <div class="flower-loader">\n        Loading…\n    </div>\n</div>');
    $el.appendTo('body');
    return function(err, next) {
      if (err) {
        return next(err);
      }
      this.view.on('beforeRender', function() {
        return $el.show();
      });
      this.view.on('tplBeforeUpdate', function() {
        return $el.show();
      });
      this.view.on('render', function() {});
      this.view.on('tplUpdate', function() {});
      return next();
    };
  });

}).call(this);
