// Generated by CoffeeScript 1.9.3

/**
 * loading 效果
 * @module middleware/loader
 * @author vfasky <vfasky@gmail.com>
 */

(function() {
  "use strict";
  var $, $el;

  $ = require('jquery');

  $el = $('<div class="loader-wrap">\n    <div class="flower-loader">\n        Loading…\n    </div>\n</div>');

  $el.hide().appendTo('body');

  module.exports = function(err, next) {
    if (err) {
      return next(err);
    }
    this.view.on('beforeRender', function() {
      return $el.show();
    });
    this.view.on('tplBeforeUpdate', function() {
      return $el.show();
    });
    this.view.on('render', function() {
      return $el.hide();
    });
    this.view.on('tplUpdate', function() {
      return $el.hide();
    });
    return next();
  };

}).call(this);
