// Generated by CoffeeScript 1.9.3

/**
 * 编译模板
 * @date 2015-08-25 09:37:14
 * @author vfasky <vfasky@gmail.com>
 * @link http://vfasky.com
 * @version $Id$
 */

(function() {
  var defOptions, reactTools;

  reactTools = require('react-tools');

  defOptions = {
    target: 'es5'
  };

  exports.transform = function(html, options) {
    var arr, code, js;
    if (options == null) {
      options = defOptions;
    }
    arr = html.split('\n');
    code = "" + (arr.join(',\n'));
    js = 'return ' + reactTools.transform(code, options);
    console.log(js);
    return js;
  };

}).call(this);
