// Generated by CoffeeScript 1.9.3

/**
 * attr ext
 * @module mcore-attr
 * @author vfasky <vfasky@gmail.com>
 */

(function() {
  define('mcore-attr', ['mcore-attr/validator', 'mcore-attr/scroller'], function(validator) {
    "use strict";
    var exports;
    return exports = {
      validator: validator
    };
  });

}).call(this);
