// Generated by CoffeeScript 1.10.0

/**
 * dom attr binders
 * @date 2016-01-14 21:25:51
 * @author vfasky <vfasky@gmail.com>
 * @link http://vfasky.com
 */
'use strict';
exports['show'] = function(el, value) {
  return el.style.display = value ? '' : 'none';
};

exports['hide'] = function(el, value) {
  return el.style.display = value ? 'none' : '';
};

exports['checked'] = function(el, value) {
  return el.checked = value && true || false;
};
