// Generated by CoffeeScript 1.9.3

/**
 * @version 1.1.0
 * @module mcore
 * @author vfasky <vfasky@gmail.com>
 */

(function() {
  define('mcore', ['mcore/util', 'mcore/template', 'mcore/view', 'mcore/route', 'mcore/ui', 'mcore/app'], function(util, Template, View, Route, Ui, App) {
    "use strict";
    var exports;
    exports = {
      util: util,
      Template: Template,
      View: View,
      Route: Route,
      Ui: Ui,
      App: App
    };
    return exports;
  });

}).call(this);
