// Generated by CoffeeScript 1.10.0

/**
 * 
 * @date 2016-01-12 17:11:09
 * @author vfasky <vfasky@gmail.com>
 * @link http://vfasky.com
 */
'use strict';
module.exports = require('../vendor/observe.js');
