// Generated by CoffeeScript 1.10.0
'use strict';

/**
 * 放到下一帧执行
 * @author vfasky <vfasky@gmail.com>
 */
if (window.requestAnimationFrame) {
  module.exports = function(fun) {
    return window.requestAnimationFrame(function() {
      return fun();
    });
  };
  module.exports.clear = function(id) {
    if (id) {
      return window.cancelAnimationFrame(id);
    }
  };
} else {
  module.exports = function(fun) {
    return setTimeout(fun, 0);
  };
  module.exports.clear = function(id) {
    if (id) {
      return clearTimeout(id);
    }
  };
}
