// Generated by CoffeeScript 1.9.3

/**
 * React View
 * @module mcore/rview
 * @author vfasky <vfasky@gmail.com>
 */

(function() {
  define('mcore/rview', ['mcore/rtemplate'], function(Template) {
    "use strict";
    var _id;
    _id = 0;
    return function(proto, tagName) {
      if (proto == null) {
        proto = {};
      }
      if (!tagName) {
        tagName = 'McoreView_' + _id;
        _id++;
      }
      return function() {
        return new Template(tagName, proto);
      };
    };
  });

}).call(this);
