// Generated by CoffeeScript 1.10.0

/**
 * 基于 virtual dom 的模板引擎
 * @date 2016-01-09 16:39:56
 * @author vfasky <vfasky@gmail.com>
 * @link http://vfasky.com
 */
'use strict';
var EventEmitter, Template, clone, diff, nextTick, patch, ref, ref1,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty,
  slice = [].slice;

EventEmitter = require('./eventEmitter');

ref = require('./util'), clone = ref.clone, nextTick = ref.nextTick;

ref1 = require('./virtualDom'), diff = ref1.diff, patch = ref1.patch;

Template = (function(superClass) {
  extend(Template, superClass);

  function Template() {
    this._status = 0;
    this._queueId = null;
    this.refs = null;
    this.virtualDomDefine = null;
    this.virtualDom = null;
    this.scope = {};
    this.init();
  }

  Template.prototype.set = function() {
    var args;
    args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
    if (args.length === 1 && util.isObject(args[0])) {
      this.scope = args[0];
    } else if (args.length === 2) {
      this.scope[args[0]] = args[1];
    } else {
      return;
    }
    if (this._status === 0) {
      return;
    }
    this.emit('changeScope', this.scope);
    return this.renderQueue(this);
  };

  Template.prototype.get = function(key, defaultVal) {
    if (defaultVal == null) {
      defaultVal = null;
    }
    if (this.scope.hasOwnProperty(key)) {
      return this.scope[key];
    }
    return defaultVal;
  };

  Template.prototype.destroy = function() {
    if (this.refs && this.refs.parentNode && this.refs.parentNode.removeChild) {
      return this.refs.parentNode.removeChild(this.refs);
    }
  };

  Template.prototype.init = function() {};

  Template.prototype._render = function(data, done) {
    var patches, scope, virtualDom;
    scope = clone(data.scope);
    virtualDom = this.virtualDomDefine(scope);
    if (this.virtualDom === null) {
      this.virtualDom = virtualDom;
      this.refs = this.virtualDom.render();
    } else {
      patches = diff(this.virtualDom, virtualDom);
      this.virtualDom = virtualDom;
      patch(this.refs, patches);
    }
    this._status = 2;
    this.emit('rendered');
    if (done) {
      return done();
    }
  };

  Template.prototype.renderQueue = function(data, doneOrAsync) {
    nextTick.clear(this._queueId);
    if (true === doneOrAsync) {
      return this._render(data);
    } else {
      this._status = 1;
      return this._queueId = nextTick((function(_this) {
        return function() {
          return _this._render(data, doneOrAsync);
        };
      })(this));
    }
  };

  Template.prototype.render = function(virtualDomDefine, scope1, doneOrAsync) {
    this.virtualDomDefine = virtualDomDefine;
    this.scope = scope1 != null ? scope1 : {};
    if (doneOrAsync == null) {
      doneOrAsync = function() {};
    }
    this._status = 1;
    this.emit('beforeRender');
    this.renderQueue(this, true);
    if (doneOrAsync) {
      return doneOrAsync();
    }
  };

  return Template;

})(EventEmitter);

module.exports = Template;
