// Generated by CoffeeScript 1.10.0

/**
 * 基于 virtual dom 的模板引擎
 * @date 2016-01-09 16:39:56
 * @author vfasky <vfasky@gmail.com>
 * @link http://vfasky.com
 */
'use strict';
var EventEmitter, Template, clone, diff, nextTick, patch, ref, ref1, util,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty,
  slice = [].slice;

EventEmitter = require('./eventEmitter');

util = require('./util');

ref = require('./util'), clone = ref.clone, nextTick = ref.nextTick;

ref1 = require('./virtualDom'), diff = ref1.diff, patch = ref1.patch;

Template = (function(superClass) {
  extend(Template, superClass);

  function Template() {
    this._status = 0;
    this._queueId = null;
    this.refs = null;
    this.virtualDomDefine = null;
    this.virtualDom = null;
    this.scope = {};
    this.init();
  }

  Template.prototype.watchScope = function() {
    if (this.__initWatch) {
      return;
    }
    return this.__initWatch = true;
  };

  Template.prototype.set = function() {
    var args, doneOrAsync, key, val;
    args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
    doneOrAsync = null;
    if (args.length > 1) {
      key = args[0];
      val = args[1];
      this.scope[key] = val;
      if (args.length === 3) {
        doneOrAsync = args[2];
      }
    } else {
      return;
    }
    if (this._status === 0) {
      return;
    }
    this.emit('changeScope', this.scope, key, val);
    return this.renderQueue(doneOrAsync);
  };

  Template.prototype.get = function(key, defaultVal) {
    if (defaultVal == null) {
      defaultVal = null;
    }
    if (this.scope.hasOwnProperty(key)) {
      return this.scope[key];
    }
    return defaultVal;
  };

  Template.prototype.destroy = function() {
    if (this.__initWatch) {
      Object.unobserve(this.scope);
    }
    if (this.refs && this.refs.parentNode && this.refs.parentNode.removeChild) {
      return this.refs.parentNode.removeChild(this.refs);
    }
  };

  Template.prototype.init = function() {};

  Template.prototype._render = function(done) {
    var patches, scope, virtualDom;
    scope = util.extend(true, this.scope);
    virtualDom = this.virtualDomDefine(scope);
    if (this.virtualDom === null) {
      this.virtualDom = virtualDom;
      this.refs = this.virtualDom.render();
    } else {
      patches = diff(this.virtualDom, virtualDom);
      this.virtualDom = virtualDom;
      console.log(patches);
      patch(this.refs, patches);
    }
    this._status = 2;
    this.emit('rendered');
    if (util.isFunction(done)) {
      return done();
    }
  };

  Template.prototype.renderQueue = function(doneOrAsync) {
    nextTick.clear(this._queueId);
    if (true === doneOrAsync) {
      return this._render();
    } else {
      this._status = 1;
      return this._queueId = nextTick((function(_this) {
        return function() {
          return _this._render(doneOrAsync);
        };
      })(this));
    }
  };

  Template.prototype.render = function(virtualDomDefine, scope, doneOrAsync) {
    var ix, scopeKeys, scopeLen;
    this.virtualDomDefine = virtualDomDefine;
    if (scope == null) {
      scope = {};
    }
    if (doneOrAsync == null) {
      doneOrAsync = function() {};
    }
    this._status = 1;
    this.emit('beforeRender');
    scopeKeys = Object.keys(scope);
    scopeLen = scopeKeys.length;
    if (scopeLen === 0) {
      this.renderQueue(doneOrAsync);
    } else {
      ix = scopeLen - 1;
      scopeKeys.forEach((function(_this) {
        return function(v, k) {
          return _this.set(v, scope[v], k === ix && doneOrAsync || null);
        };
      })(this));
    }
    this.watchScope();
    return this;
  };

  return Template;

})(EventEmitter);

Template.formatters = require('./formatters');

Template.components = {};

Template.binders = {};

module.exports = Template;
