// Generated by CoffeeScript 1.10.0

/**
 * ui
 * @module mcore/ui
 * @author vfasky <vfasky@gmail.com>
 */
"use strict";
var $, $body, Stapes, Template, exports;

$ = require('jquery');

Template = require('./template');

Stapes = require('stapes');

$body = $('body');

exports = module.exports = Stapes.subclass({
  constructor: function($el, options) {
    this.options = options != null ? options : {};
    this.$el = $('<div/>');
    this.$parent = $el || $body;
    this.on('render', (function(_this) {
      return function() {
        return _this.$el.appendTo(_this.$parent);
      };
    })(this));
    this.init();
    return this.watch();
  },
  asyncSet: function(key, promise) {
    return promise.then((function(_this) {
      return function(val) {
        _this.set(key, val);
        return val;
      };
    })(this));
  },
  destroy: function() {
    if (this.tpl) {
      this.tpl.destroy();
    }
    return this.$el.remove();
  },
  render: function(uri, data) {
    if (data == null) {
      data = {};
    }
    return Template.render(uri, data, this);
  },
  renderString: function(html, data) {
    if (data == null) {
      data = {};
    }
    return Template.renderString(html, data, this);
  },
  init: function() {},
  watch: function() {}
});
