// Generated by CoffeeScript 1.10.0

/**
 * 
 * @date 2016-01-11 20:41:14
 * @author vfasky <vfasky@gmail.com>
 * @link http://vfasky.com
 */
'use strict';
var _isNumberReg;

_isNumberReg = /^-{0,1}\d*\.{0,1}\d+$/;

exports.isNumber = function(x) {
  return _isNumberReg.test(x);
};

exports.isObject = function(x) {
  return Object.prototype.toString.call(x) === '[object Object]';
};

exports.isString = function(x) {
  return Object.prototype.toString.call(x) === '[object String]';
};

exports.clone = function(src) {
  var dest, key, val;
  dest = {};
  for (key in src) {
    val = src[key];
    if (src.hasOwnProperty(key)) {
      dest[key] = val;
    }
  }
  return dest;
};

(function() {
  if (window.requestAnimationFrame) {
    exports.nextTick = function(fun) {
      return window.requestAnimationFrame(function() {
        return fun();
      });
    };
    return exports.nextTick.clear = function(id) {
      if (id) {
        return window.cancelAnimationFrame(id);
      }
    };
  } else {
    exports.nextTick = function(fun) {
      return setTimeout(fun, 0);
    };
    return exports.nextTick.clear = function(id) {
      if (id) {
        return clearTimeout(id);
      }
    };
  }
})();
