// Generated by CoffeeScript 1.10.0

/**
 * simple-virtual-dom
 * @date 2016-01-07 21:50:58
 */
'use strict';
var Element, diff, el, patch, ref, render;

ref = require('simple-virtual-dom'), el = ref.el, diff = ref.diff, patch = ref.patch;

Element = el;

render = el.prototype.render;

Element.prototype.render = function() {
  el = render.call(this);
  console.log(el);
  return el;
};

module.exports = {
  el: Element,
  diff: diff,
  patch: patch
};
